capstone/Activity/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

capstone/Activity/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

# Syntax
# path(route, view, name)

urlpatterns = [
	path('', views.index, name='index'),
	#/todolist/<todoitem_id>
	#/todolist/1
	# The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/register
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_view, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('<int:todoitem_id>/', views.todoitem, name="viewtodoitem"),
	path('<int:todoitem_id>/edit', views.update_task, name="update_task"),
	path('<int:todoitem_id>/delete', views.delete_task, name="delete_task"),

	path('add_event', views.add_event, name="add_event"),
	path('event/<int:event_id>/', views.eventitem, name="vieweventitem"),
	path('event/<int:event_id>/edit', views.update_event, name="update_event"),
	path('event/<int:event_id>/delete', views.delete_event, name="delete_event"),
]

capstone/Activity/todolist/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class Events(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

capstone/Activity/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class RegistrationForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	firstname = forms.CharField(label='Firstname', max_length=20)
	lastname = forms.CharField(label='Lastname', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="status", max_length=50)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="status", max_length=50)

capstone/Activity/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.forms.models import model_to_dict
from django.utils import timezone


from .models import ToDoItem, Events
from .forms import LoginForm, RegistrationForm, AddTaskForm, UpdateTaskForm, AddEventForm, UpdateEventForm

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	event_list = Events.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'event_list': event_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)

	# template = loader.get_template("todolist/index.html")
	# context = {
	# 	'todoitem_list': todoitem_list
	# }
	# return HttpResponse(template.render(context, request))

	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# return HttpResponse(output)
	# return HttpResponse("Hello from the views.py file")


def todoitem(request, todoitem_id):
	
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))
	# todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))

	# return render(request, "todolist/todoitem.html", todoitem)


	# response = "You are viewing the details of %s"
	# return HttpResponse(response % todoitem_id)


def register(request):
	# users = User.objects.all()
	# is_user_registered = False
	# context = {
	# "is_user_registered": is_user_registered
	# }

	# for indiv_user in users:
	# 	if indiv_user.username == "johndoe":
	# 		is_user_registered = True
	# 		break

	# if is_user_registered == False:
	# 	user = User()
	# 	user.username = "johndoe"
	# 	user.first_name = "John"
	# 	user.last_name = "Doe"
	# 	user.email = "john@mail.com"
	# 	# user.password = "john1234"
	# 	# The set_password method is used to ensure that the password is hashed
	# 	user.set_password("john1234")
	# 	user.is_staff = False
	# 	user.is_active = True
	# 	user.save()
	# 	context = {
	# 		"first_name": user.first_name,
	# 		"last_name": user.last_name
	# 	}

	context = {}

	if request.method == 'POST':
		form = RegistrationForm(request.POST)

		if form.is_valid() == False:
			form = RegistrationForm()
		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			firstname = form.cleaned_data['firstname']
			lastname = form.cleaned_data['lastname']
			email = form.cleaned_data['email']
			# print(user)

			context = {
				"username": username,
				"password": password,
				"firstname": firstname,
				"lastname": lastname,
				"email": email,

			}

			users = User.objects.filter(username=username, email=email)

			if users is not None:
				User.objects.create(
					username=username, 
					first_name=firstname,
					last_name=lastname, 
					email=email, 
					password=make_password(password), 
					is_staff = False, 
					is_active=True)

				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/register.html", context)


def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="johndoe", password="johndoe1")
	print(user)

	if user is not None:
		# user = User.objects.get(username='johndoe')
		# user.set_password("johndoe1")
		# user.save()
		# is_user_authenticated = True
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, "todolist/change_password.html", context)

def login_view(request):

	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()
		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			# print(user)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				login(request, user)
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/login.html", context)


def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):

	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)



def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status,
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)
		if form.is_valid() == False:
			form = UpdateTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:
				context={
					"error": True
				}
	return render(request, "todolist/update_task.html", context)


def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")




def eventitem(request, event_id):
	event = get_object_or_404(Events, pk=event_id)
	return render(request, "eventlist/event.html", model_to_dict(event))


def update_event(request, event_id):
	# response = "You are editing %s"
	# return HttpResponse(response % event_id)
	event = Events.objects.filter(pk=event_id)

	context = {
		"user": request.user,
		"event_id": event_id,
		"event_name": event[0].event_name,
		"description": event[0].description,
		"status": event[0].status,
	}

	if request.method == 'POST':
		form = UpdateEventForm(request.POST)
		if form.is_valid() == False:
			form = UpdateEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if event:
				event[0].event_name = event_name
				event[0].description = description
				event[0].status = status

				event[0].save()
				return redirect("todolist:index")

			else:
				context={
					"error": True
				}
	return render(request, "eventlist/update_event.html", context)

def delete_event(request, event_id):
	event = Events.objects.filter(pk=event_id).delete()
	return redirect("todolist:index")

def add_event(request):

	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			duplicates = Events.objects.filter(event_name=event_name)

			if not duplicates:
				Events.objects.create(event_name=event_name, description=description, user_id=request.user.id)
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "eventlist/add_event.html", context)

capstone/Activity/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">
						Duplicate task found
					</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
					{% csrf_token %}
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">Task Name: </label>
				    	<input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" required>
				  	</div>
				  	<div class="mb-3">
				    	<label for="exampleInputPassword1" class="form-label">Description</label>
				    	<textarea class="form-control" name="description" value="{{ description }}" required></textarea>
				  	</div>
				  	<input class="btn btn-success" type="submit" value="Add Task">
				</form>
			</div>
		</div>		
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}

capstone/Activity/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>

{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>

{% endif %}

capstone/Activity/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

	{% if todoitem_list and user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<div class="row">
				<h3 class="text-center mb-3">My Tasks</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% for todoitem in todoitem_list %}
					<li class="list-group-item">
						<a href="{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a>
					</li>
					{% endfor %}
				</ul>
			</div>
			<div class="row">
				<h3 class="text-center mb-3">My Events</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
					{% for event in event_list %}
					<li class="list-group-item">
						<a href="{% url 'todolist:vieweventitem' event.id %}">{{event.event_name}}</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

	{% else %}
		<p>No tasks have been created.</p>
		
	{% endif %}

{% endblock %}

capstone/Activity/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Login</h1>
					{% if error == True %}
						<p class="text-danger">
							Invalid User Credentials, please check your username and password.
						</p>
					{% endif %}
				
				<form action="{% url 'todolist:login' %}" method="post">
					{% csrf_token %}
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">Username</label>
				    	<input type="text" class="form-control" id="username" name="username" value="{{ username }}" aria-describedby="emailHelp" max-length="20" required>
				    	<div id="emailHelp" class="form-text">We'll never share your Username with anyone else.</div>
				  	</div>
				  	<div class="mb-3">
				    	<label for="exampleInputPassword1" class="form-label">Password</label>
				    	<input type="password" class="form-control" id="password" name="password" value="{{ password }}" max-length="20" required>
				  	</div>
				  	<input type="submit" value="Submit" class="btn btn-primary">
				</form>
			</div>
		</div>		
	</div>


{% endblock %}

capstone/Activity/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Register</h1>
					{% if error == True %}
						<p class="text-danger">
							Invalid User Credentials, please check your username and password.
						</p>
					{% endif %}
				
				<form action="{% url 'todolist:register' %}" method="post">
					{% csrf_token %}
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">Username</label>
				    	<input type="text" class="form-control" id="username" name="username" value="{{ username }}" max-length="20" required>
				  	</div>
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">First Name</label>
				    	<input type="text" class="form-control" id="firstname" name="firstname" value="{{ firstname }}" max-length="20" required>
				  	</div>
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">last Name</label>
				    	<input type="text" class="form-control" id="lastname" name="lastname" value="{{ lastname }}" max-length="20" required>
				  	</div>
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">Email</label>
				    	<input type="email" class="form-control" id="email" name="email" value="{{ email }}" max-length="20" required>
				  	</div>
				  	<div class="mb-3">
				    	<label for="exampleInputPassword1" class="form-label">Password</label>
				    	<input type="password" class="form-control" id="password" name="password" value="{{ password }}" max-length="20" required>
				  	</div>
				  	<input type="submit" value="Submit" class="btn btn-primary">
				</form>
			</div>
		</div>		
	</div>


{% endblock %}

capstone/Activity/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}To Do{% endblock %}

{% block content %}
	<div class="container text-center my-3">
		<h1>{{task_name}}</h1>
		<h3>Description</h3>
		<p>{{description}}</p>
		<h3>Status</h3>
		<p>{{status}}</p>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back To Tasks</a>
		</button>
	</div>
	
{% endblock %}

capstone/Activity/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}
	
{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">
						Task Not Found
					</p>
				{% endif %}
				
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}
				  	<div class="mb-3">
				   		<label for="exampleInputEmail1" class="form-label">Task Name: </label>
				    	<input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" max-length="50" required>
				  	</div>
				  	<div class="mb-3">
				    	<label for="exampleInputPassword1" class="form-label">Description</label>
				    	<textarea class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
				  	</div>
				  	<div class="mb-3">
				    	<label for="exampleInputPassword1" class="form-label">Status: </label>
				    	<input type="text"class="form-control" id="status" name="status" value="{{ status }}" max-length="50" required></input>
				  	</div>
				  	<input class="btn btn-success" type="submit" value="Update Task">
				</form>
			</div>
		</div>		
	</div>

	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}